# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
lists = [1, 2]
result = [1, 2]

while result[-1] < 4000000:
    a = lists[-1] + lists[-2]
    result.append(a)
    lists[-2] = lists[-1]
    lists[-1] = a
del result[-1]
print(lists)
print(result)

final = 0
for i in result:
    if i % 2 == 0:
        final += i

print(final)
"""

